// auth module
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'

// user module
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

export const USER_FETCH = 'USER_FETCH'

// application module
export const APPLICATION_LIST = 'APPLICATION_LIST'

// article module
export const ARTICLE_LIST = 'ARTICLE_LIST'

// licence
export const LICENCE_COMPLETE_STEP = 'LICENCE_COMPLETE_STEP'
export const LICENCE_UPDATE_CURRENT_STEP = 'LICENCE_UPDATE_CURRENT_STEP'
export const LICENCE_UPDATE_KEY = 'LICENCE_UPDATE_KEY'
export const LICENCE_UPDATE_COMPANY_NAME = 'LICENCE_UPDATE_COMPANY_NAME'
export const LICENCE_UPDATE_OWNER = 'LICENCE_UPDATE_OWNER'
export const LICENCE_CLEAN = 'LICENCE_CLEAN'
